### ISSUE TITLE
Modify or remove talk proposals

### ISSUE THREAD

**Issue by justwheel** [puiterwijk/regcfp#46] opened 2016-02-16 13:00 UTC
After someone submits a talk proposal, they are unable to edit the proposal. They should be able to modify the title or description up until the deadline.

They should also be able to edit tags and co-presenters, but this is referenced in issue #17.

**Comment by jwboyer** [comment] 2016-02-29 21:05
Just a note to highlight something @jflory7 that might be overlooked: "up until the deadline".  From an admin point of view, we need all modifications to submitted talks (including removals) to only be allowed for admins after the deadline so we can begin to sort out the schedule.

**Comment by jwboyer** [comment] 2016-03-24 12:03
So issue #50 was closed as a duplicate of this, which is fine I guess but there was an important distinction between the two.  This issue is focused around individual contributors being able to remove or edit their own talks, which is certainly needed.  However, administrators need the ability to remove or edit anyone's talk.  As long as both tasks are covered I'm fine with using a single issue.

**Closed as completed** 2016-04-05 14:27 UTC
Labels: enhancement, Module-Papers
