### ISSUE TITLE
admin: Add ability to delete talks

### ISSUE THREAD

**Issue by jwboyer** [puiterwijk/regcfp#50] opened 2016-03-08 15:23 UTC
There is currently no way to delete submitted talks.  This functionality would be very helpful in the following cases:
- Duplicate talks are submitted
- A talk is submitted twice, once by each co-presenter (special case of duplicate)
- Similar talks are submitted and then merged as a single talk with multiple presenters

**Comment by kittykat** [comment] 2016-03-24 11:46
This seems to be a duplicate of #46

**Closed as completed by kittykat** 2016-03-24 11:46 UTC
Labels: duplicate
